# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GZfD8I4JM9aOSgwhG9Gv5T/C30X3,iv:Vj/rzBpRo10RBByrZUjN6VOiiFLWt8ttRzeO6WKaWmA=,tag:BgNasL6mgfwFEq2Cvwb8pA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:HjQxWEfkiU/rt7Yfejq2QjpWWyILIGeywZRO6cmBRjPehCaFBA==,iv:ik6t5ObxZSrtMcSonVBwdASnI+5D+tVrI2/7NkfQlpM=,tag:0bhKIDtYMqK7ZVVsf9Cw8Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:ocTFGp3T1PIw/StPmaWS02Vm,iv:0RS5FRk3LPaGB7+QA+EYoFK7IuXaABHsdmjCVob+nYM=,tag:9fZfi8Q/a8roHwy0XUq+iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYkdEZWFuVm9sbzUyZUF0
            R0JHM2xYSDNLRTBCL21YM0ZTQUluWGJHa3lRCk1IVU4vRnIxM3kzbmNubW42OTZQ
            MnNEekc2SU1rdGw3emxpTEVXWG1KRE0KLS0tIG5pZGc5WklVOWsxc2NnaU5WT0xj
            ZTdqK0Vvd0xtOXVSaHF1T0ZEcGkxSEkKF8bk5FRtbSVjPT+bOAAle3vJ8Mr/rcuH
            BR+IzNKzYOGAjvhw04oaWVmR6qk6idMAx1/M2sUPsKgiL8yHEpsnVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-12T00:32:51Z"
    mac: ENC[AES256_GCM,data:Lw3tB4w9ylbDClieG1x5TnRZUqjk1Dm8s7Rk7zIeW9nGp+zBMBtuIDiiivzv4R/G86XlylNu9sRksm3mWzaturcr9STqsNBCyPAv/961V0zf7SGpoE9uJJ8IbBBIvtW+weuJ7UOOsVUqpNBdqiEVIMzrtGTaYrBXkrgYvFD+tQc=,iv:4EQelhB4mh5mxLWmJ04/XV28vf4OrG2PnJVIh278WN0=,tag:HxTLWd8kuf3BbrWf6zrOfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
