# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:EYO2Bha7a9NFdDLy51uf/f7pt2yQ,iv:y4qsY0l6PqH1RVJYi1Xh+bP9K7uQw7ax4NaDJvF8Sp4=,tag:CwgAGCgT0KbdVRudqCuG7w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:AmIboYVbRJHFHWEVexwJZj2Ow077pzclGvNL5meqKOvprZL/Tg==,iv:bRTVIhcBjh76yPDSHOQY3QH9nUuUICpvMDedUg+teSI=,tag:Sc5S+szlcdxp0c0yhNm4Xw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:JSoq+yy3LLVTyr4xUevCa3RE,iv:xh001srURINwYc6KcspdzuMxOpdcmt49rkli2f6RnLM=,tag:iEgMG0VG9lKAfiAoLH3abQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta3dWVk9vOE9sNnBhV1RG
            N3RObW1leStla2QzdG44RlMvbWh5NXFSZkZ3Ci9VSWRzWG11R3dLRnhGQjBGV2R0
            aWpqUkEyTjRhbDJyZUpSRHZXbEFzMmcKLS0tIDdHMUdka1JNVjV6Mk8wTlVIWHdy
            dzdGNlEzU2YyS1AvendwUE9TZlNlNEUKTbID5agb+tU0/Sd4vpt2yr8td3xVV0Wm
            ScZzZFKxRqEqYHDJZ8GPPeMwgqtIwHVblShDgZLeK/DkXtCpd5KPLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T00:54:35Z"
    mac: ENC[AES256_GCM,data:5Ruc1gTB+WKYC5PE0iJdhzYqQM6BN9hjBr55i1Phut8Zl4fzI33eB4IdcZRiZDX9sGIBJ9Ol5NHeTudz+iJhihh31y1cbXG22VhQikYAr2b1LMxnU00oS4MKnMxkRbw5AyshNSGqFXup0oIMvRYc+ybtAOzi4VhrowG0gKJRTks=,iv:j1us/S14vmyLtgQTlq0Cz/Okv6S6rA1xmyoOms+k83k=,tag:FG7lG1ie+qHPoMfbuLuflA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
