# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:e7tYeTqPeGgXkXN3diCh5WKrktuo,iv:TWUqwJ1Da6kcTH7AIQKYhBLNbh0LVql7mrpXARD9N1s=,tag:Eu25ViI88Dl6jokAANFHYg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:1ut3Wa78CsgyCrSjIo/xYqUS4SJLmsGTmyc0rUOUyvKr/bHjLw==,iv:GiMoctuUCOTlHIsR3dD1XBfdSftmWWkVXyUnRyVOjUg=,tag:/VcEJ9DYwSB7cHpEXMjniQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:qlQhWi0KzSQhYHV7H00oidIV,iv:kjPKdt5zvWZstiB1msX+RpCNUL9GQJ+8nwfzIGLN/2Q=,tag:BRM63uWtU4G5ROSsfOdEMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQXIzazEvYVZlc1ZmT0dN
            LzM0Q3ViNEtSNDVsZEJqZTZOUU9ZNjA5V0hzCmN1UVZ5eFVmV1kwV210TzgzTWtM
            b1c2ZDlSU2hCY2VaQjErcHQ1cElhSVUKLS0tIHA0TzZpTy9NVjFhWk5YWFJDZVF1
            OFVOaXZuL2s5TnpRT1FxOFN4Y2g2NWMKQFDtfAFQJ1F1TpM5+eQWLJUulCnta8oC
            RANuVpyV1gKS6Mgsa7SXiWtP18tXztZZl91asPNawBDVQkjNHoS0XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-13T20:13:29Z"
    mac: ENC[AES256_GCM,data:7hX4zmfOD8+kFLpVnDYv+r+ecmSBk948LNJWOEXDceH6gSQ1JTa/u1sfgSvjSt6wQGxclpfZ+/xHyckqEj2zne4b9RlvsT45wyoKevcbRE1bw91CZibyTZW7g3Stj5LmB2eHDGU8IQoBTjjoOR0TD6WiZtqkF+4fI7V+mcbWiYI=,iv:XDmrtHqXq6Sj6hme+ShrPI6xTrB1iGNCkuJhiefTJL8=,tag:w77TEuzCrRWKxuxFqyxhVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
