---
kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
          ansible_host: 10.0.1.11
        k3s-master-1:
          ansible_host: 10.0.1.12
        k3s-master-10:
          ansible_host: 10.0.1.33
        k3s-master-2:
          ansible_host: 10.0.1.13
        k3s-master-8:
          ansible_host: 10.0.1.31
        k3s-master-9:
          ansible_host: 10.0.1.32
    worker:
      hosts:
        k3s-node-11:
          ansible_host: 10.0.1.41
        k3s-node-12:
          ansible_host: 10.0.1.42
        k3s-node-13:
          ansible_host: 10.0.1.43
        k3s-node-14:
          ansible_host: 10.0.1.44
        k3s-node-15:
          ansible_host: 10.0.1.45
        k3s-node-3:
          ansible_host: 10.0.1.21
        k3s-node-4:
          ansible_host: 10.0.1.22
        k3s-node-5:
          ansible_host: 10.0.1.23
        k3s-node-6:
          ansible_host: 10.0.1.24
        k3s-node-7:
          ansible_host: 10.0.1.25
