---
kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
          ansible_host: 10.0.1.11
        k3s-master-1:
          ansible_host: 10.0.1.12
        k3s-master-2:
          ansible_host: 10.0.1.21
    worker:
      hosts:
        k3s-node-3:
          ansible_host: 10.0.1.22
        k3s-node-4:
          ansible_host: 10.0.1.31
        k3s-node-5:
          ansible_host: 10.0.1.41
