# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:uM1UtWkgfLkdQNlHSaLX4RFnVl5C,iv:PwUxu6z1B8G95fvwSE4DAYwzyKWWNaH4tnMtqBX8yCk=,tag:ZcSb13QWyevA0hllVqgpVA==,type:str]
    api-key: ENC[AES256_GCM,data:MeBP2bn0J6WwTDfMyVx8+R1Fh16oM+USLFlpCyMqyVRAz989cA==,iv:RRboRPqE/oN+K0h9EsqqHpbHwK8Y3r62yYuZ3MWnrFE=,tag:KwUd+XZB7+LkzkKsEtwouA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORGpGZEF3MTFSWnNDZlZK
            RkRqc1g4QUVlRnJ4c041RkEvb3orWHdYWkFRCmh3TmxiVUVUNE41MTJUa2VDYzFQ
            d2JqbFN3UThIdUNQOE9TTXlFSTFENDgKLS0tIFBnWVNmeUdIZUYrZkNLUkNuS3Yz
            d29GOUswc0kwc1JicW8rNVI4S1BsTFUK5ZF9+3/ToK+eMLH4o/tguAIH32yDW4qM
            6Bi+dcxBXbRMiIwHhLfmp5SMjZyJRHhYZXBRpwPxgfDuQ5+/nM2dgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T14:59:51Z"
    mac: ENC[AES256_GCM,data:F+hjZm/oDTWoL7SEXsTs6ZxeOKoiMEV1FLMNCC6O40a/o70zZgiyg+RX5OtH4jittSrq/31oea5g3wqx63SNYb1cv2nehD0odqmwxSDTWqRLKwqWKkDBrdC8O9ObkyszrrI9MHpmj/0djqMOVxRlDWVNKPvMErskqnbZS9LKJRc=,iv:+JC3wnkqxZV41RtrQrZNXnbWv+2WmWxa6cUgBwNkRc0=,tag:hMyZwiYjXIEvgImXCshlNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
