# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:xhLuPDRQ6CqQUZCm90CVdfuZK63E,iv:aUGDrj+E/a95rKrWrKxe2jixnEttnDZ6MbsQN2E0r1w=,tag:CPQJ3zCFIJftkouIdxzsFA==,type:str]
    api-key: ENC[AES256_GCM,data:BQ6bOlVoq7H+Sq0h4JJ98IFJPGrIkeE0oB+/RsTNU8jHwup0PQ==,iv:TgsmqbQj/t+8yOfXAhEnITomKjWePb6TtmO+KvrM9Us=,tag:pBxuSh9kZ46yViqdC1wULg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL1JEMmhsSVFxMW9IcDdY
            Q2VZQk9jZ054NFNpRkhjcTVxaGYxRGppRGlNCkpseDdqSlBTREhTQjB2M3Zqc0s1
            Ly9DMk5QZlRhKzJ2Qmt5dlFYQlA5anMKLS0tIFBmNFoveS84bWxNeUt3OThobGlE
            bC9yYmFrM2t0U24xWkY0eFhUb2oyV2cKGY/exQM7+8A8Ji2iaQCw8UW8v2QxTRkt
            mr+k/0Pk7lFL/a+ER44VZOaun+ZRVpzR1X2+jpy2hBEJey4Kxst16w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T23:24:58Z"
    mac: ENC[AES256_GCM,data:rFTI5qSakLA/P5Uh3DcQuqimvfgkBb07/Oa74azCxauUX8ENd4J4pCThlA3N3SbTiLxF5qJg1FwNTZxUnkTBPf2Hl/9p39TX3Wdn3eojsVPoyU+fNRBzGFjg0yfoTHD3VhEcymoWCjxSuOn9ZOfPxBQEXoTkulmdIt0uD2yhdy4=,iv:XUeuNi1OGor78wrP6OjEfz6CIsgZVBc73c/n8OUFHgU=,tag:1JkQ09Zwm1oI6Py7Eg5E1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
