# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:H+lKeByACxGnSlsYbn+6+X2qwKat,iv:CZ9YHy0kKWno+6u9pn76nvSB5axmPvQFNjaGauMDBlU=,tag:8P00gjqBoJVI63qYmD2FRA==,type:str]
    api-key: ENC[AES256_GCM,data:PrMcun9wS2kDwNwqxWwfQ30lgvoW5skZ6f2QDwTiNaPTOSBESg==,iv:tTkPW26QOBKe7RGsZbhXVEiT2Z4re3RdyhCPy3fWohc=,tag:rA1EKtBsus70Nw57IHzJpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNVNxTjZwQUFvL0pTY1Bi
            MzRZS2t0MEsvcWNwaXFkNWV0NVNhSFpvMFd3CmtlK2pLQWwzRVNmZUxXaGdRSCtj
            c1cwQnJKZ2tjL0NUeDlLdkwvRWkrYzQKLS0tIGNDdzZ5emFFNXlYamF5dHFiVzNB
            MUg0Uy9ranRVQ2VmR0s3UTZsejBuZUUKJevWXvkHGsylIqD0Yz9nl+PjaiEGpkyv
            xhECoRcjFviSRBM6GocE9D9AQC9QJiAakQ5+neei46E8BiMXkwDQvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T22:16:04Z"
    mac: ENC[AES256_GCM,data:AuX4LG8+ikBu8KY/sH0zWNy3HxogKXQIxM15lR2QweVMRxPO1GWw4OOlEUS3qVPdrJIVjKMgKu7YlMn/09Ury4lBVdJD671TVO+/gbQGPr5I0kAotBC+r6KfmOl/QfvsK/TTu+7JFJVfQ2nhhtlT0XclS/+T41GfP+3t+pDqQk0=,iv:zglD14yxdrQCbMiO+3AcMptxEy7gmPgsi6s6oRP3bkU=,tag:n7ngzm2RC2fi2HKhA/8qiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
