# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:C+iyS/Vk32zCjIUkx40cEU+VrPjZ,iv:U7SElgAgDRfn0nTcz6+Wny8h6jy00ybupCmAqU5ehvk=,tag:VF61BkpRDNV7gM5ClwTcIw==,type:str]
    api-key: ENC[AES256_GCM,data:OAnCh00ZPHM0hlTkctTiVdQl9MAFTK9ia2tTebnG41kqUsmSAw==,iv:EDVlNkwg5RbQyjzrl3ERdugCxKsb+Gy3IFR4h1izOTQ=,tag:a1/ELnvV8x/BL2bZBUIYHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRmNwbkVienZnNmpRNXBQ
            UnJCTk42aVJXWTBwaUtPNXZOWWRvVEhEZEQ0CmJYZ0ZFSDh1K015NDQ1cEFGMkRj
            NDE3UVVQMHM2ZjZzaFNOMGF2MS9sYm8KLS0tIDhVdGMxZ0h6cDdPb3d5eGkrTmdv
            YWNPanZMeTU3N2FibE9ad3ZObUd1cjgKojQJK63g1/16GWDORsV1vrqgYoZYwpGy
            7Fa4hEPWbG8jS7agRkW67/7UPoV1iUl3n97rPgj9J+Xbu5iH0jUSZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-12T00:32:51Z"
    mac: ENC[AES256_GCM,data:tXqQofaRbnpVAMNdyJXtDxfTdQkL1awRwyEqLJRdW3T/euRlPgD4ZymB6MXxlX8HOKdTL5Sl2pkFsav/P5E+qTtFSZLviclmbOYmxHy8vWcZ+tDD0op3sWS8/EFxTGsSDU44JsB7ANs2rLfAgz9DU2n2YYsA3kXuKbYq6igLQdQ=,iv:vHzF7cQR2WMo6BnEQL3ZNRPKeL/5BqiImqOrw/TTdQ8=,tag:Mk/g6Ho9jI1qxK/hdAE2dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
