kind: Secret
ansible_user: ENC[AES256_GCM,data:7Gw38rXhllA=,iv:lcqkBcBjFH1LJ6RmjvdHomx2UQS7OHpZ9blzJeeYxVU=,tag:vGwNNZcQs99WY8Bk7nb7Pw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5wqzUkkiiA==,iv:pYyeb1oDZYUXZJcA7eOkP3h6rEnLMxGWMQA1iG02jcY=,tag:yfsR/kPExeAhb/91atIG4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dkZ0aVVKS09vYisydG80
            dVFqamVQdDE2R0ZYZ1BNZXAyQ1MvU0d3TXprCnE4aDB6aXE1RUZPZDJHYnE0OTBh
            L295QlZ5R3ZLajEveFZlQ3lmMEthZ2cKLS0tIDNCWU11ZEVwRFdRTlZPQk5aOFVt
            eFlrWmg1ZEtKWTBXZThBQWN5NlNRZ3MKdF145D8ApYm59FC+UU4/P8I63OrQW+yQ
            soJgMQ7YWiDf1ypg5s8vL96IAXXSscju+6FmKEPmLSktTEGVojn5BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T23:03:25Z"
    mac: ENC[AES256_GCM,data:/pmU/ap2n8cQS+ZxR1JpGeLz0VYCSzcGCAV1uYvB8VDuaDELiVem3ox13enEKAtPviNTv7+HuPFfy4k5Yae789KOshLurbcPSGFUVV/8/sl2s3GX3Lajw1no6XnGnVjKZs82GATk9XtvBPYRfjU0McGGWbiMYfEb1yf2GXTX8cg=,iv:sSyLEfLPkLUQQ71YsdO6trBPSMpUwEh09TZApybSkS0=,tag:2zzBTKB9GCVL3O5Z6lYISA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
