kind: Secret
ansible_user: ENC[AES256_GCM,data:w9725czQUpY=,iv:g8Xl1qL5ebOAU3jRopdqKPImyt6ofJme+Sm9XEp9DOM=,tag:cnHwrF93Xt5V+Hoyh3tqvQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aaiDsX2g1g==,iv:KCt5GJMDJjpa7cNDQ/nzWrNJoZxLegjWA7/SjL5kCA4=,tag:Zl/KZ0pQD0wiGabntdE1kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMW5jRU8wZ0trQmFRNzBN
            TU9tZzVlRklkanUwQlNCWXlTTUtjYnFMZm53CkFWVzJiOWdlZSsvS2ZaK2c1bENh
            SURZWFIvL2c4YkpmazdXVko4dGNYRjAKLS0tIGpLcVpnVzY4azhLK0Q4Um1yVHZs
            NXoyQlc3NExPN0h2R1Q5S2l2L2ZINkUKw4K35DfEuhbSPDFrV2klE6M0tqzNwI+I
            NUJQjwZ3pKOOpTmz52LJXQg02Ev1qUWUHSuW3JbohDGz/1Wd3A3yDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T22:16:04Z"
    mac: ENC[AES256_GCM,data:cUR5HsPe348oWVbksy8Vj06f8wnFxOcugi4IoSHJWf6oRMhcgZZjUANYTB1hlcHmwCttFTwTxBLyUaF99XqVf1G5kV0AoTj7TNr+0U1Fs4mmaRoljkOJPZTscVqNdzGfOPa34oOejFyi2PR+GMncDeqHRMG8lNgH5ktAVeoiVMY=,iv:9EPKLoSh+8Mm1xmOMIhpwW0y1UWBcPuN+Wy0Fe8G4TA=,tag:cwajXcZqEeOIvz9WrutY/Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
