kind: Secret
ansible_user: ENC[AES256_GCM,data:uASXywIaGnE=,iv:42T1D9+lny/x5PO8Qy8bh1sVaSuIdaZ+l9E+Yibwl9k=,tag:p/wLtMBcgWZxR7vid09cYA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:dwyNoGP0Tw==,iv:vWVcNX3qg5nE3zdvpEPELRJnl1AK9ZNXwYycYS5L+Hk=,tag:1Gd94bQqA0hS/kk0dohdaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbys1SFRaSzUvZTkwcUlr
            TWpoNjIvVmFsZnB1TDJzc0pVUkRWSnpLaUE4CkhXOEpyMnJ6ZjJod2hIOEo1N1g5
            YnZnYmxacThwblJWRzlWZURVNk5JQ0kKLS0tIENCampLVS9wYVdvejJPV2NMTWd5
            R2M4NlJ6Y0VzemUrejVRNVBmRkZDbjAK90o2W3bIYAZRIwZ5s1+7uC0lEDHrOx2f
            pJalG4/xhF7Iw6LSHGzK3ZNDhr7Y0wiHa1pyiGJmxyYNDE8fyT2iZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T17:26:33Z"
    mac: ENC[AES256_GCM,data:SjsHpIMuNmD8crOrhWFqB6F1TVV+PGKgY9+ozWv/KYH3AtlyRTjwsPW7Z+zEbkWyUCdgDNu/QAIJDp7v9KNgfa41y7A6ogx9Dw9Z+axiddTRhl45Q5hzTSZkedtxTmDTE5sXG35PqjMvx0C8RZVwIqIJZZV5rLgMtb/ZXtay6/U=,iv:MFkDhU/WQIjAOCFpVteLzLE0TRgk5zqjcRAO2HXbuf0=,tag:Em6C1vOdMKNxAyOFJ0ymOw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
