kind: Secret
ansible_user: ENC[AES256_GCM,data:pRJL8aFJPGI=,iv:FKJ5lOomj+YJofA1NJpXCFW61H1vnAZpcF+wIW2dQoc=,tag:ojW5Ha7zUekdWngJHRcVzg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0HWcsBF34A==,iv:vX4ISNF4c/bjAlxTly04sEVEqzLvGrAbKNZYh0TJHio=,tag://ivEg/Jg2+3Z0xtFPoJYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV3prNWswL1JwS2k4MFB2
            UTFxbkQ1L0VHL2cwTi9nT0UreEowVUsybzFJClpHdHkrbUlWTm9FMFVNcG5UZkJG
            Y1U5ZUwxZkRFM2dGaTVnMTN1dmdsQ0UKLS0tIGQ5UmtpZTdKTnAyTCs1cXVYTUxL
            T3c2MWlOaStHejdndU5seUs5dkgxUW8KEH2dT1OVEPouJQCRwd2puRvky6U4kfIs
            0E+Bk8Pscq4nPlecFJTbAAPWKHRqCf3C2J0KgwZ+/MNku/QNqXjHPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T17:26:33Z"
    mac: ENC[AES256_GCM,data:+/JZv+3cf3a7OEYWEKKMb6SOjkB3zNS/D2V4aIc3Xl6kVxLKMeex9b5zf80EBlqGkqv7lt6Qmco8VTO1Oy3ou7jWQXKVSKQlaK2IlxOwZr7gMJjebKqclGrampQrd3l2GLefchAQb1icbXo1R1JvNlRV+qsOh9oNJvEjxjhAqDg=,iv:LcpNZ9kOT/Ko4CHMLxKN54p7E3xao+G2JYXzyo5e5JU=,tag:K60Tv7pw/An6AmfK0MPlWA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
