kind: Secret
ansible_user: ENC[AES256_GCM,data:PToikuMnvzo=,iv:3NTBdgxaG8qi4ze/S1s4IeUE2dVPTUy+fmuKG6Y5F/I=,tag:YSG7bFYq3vQpszMheRWvgw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6FLvtiHX+A==,iv:OfydxfzsCcTWp3qu8aj2kLGBeoLhRb+lI7ukf1HJU3I=,tag:3wx3VtVowq3WlWGWcsxa9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd1hEVHQwM1U2dDFnUk4x
            eDJrVm56VFZmVEdmM1IxK3hkaGRFU0R2MHlrCnV1WVI2L2pnQyt4cGQ3Z0RjV2Qx
            SjBrK0FGZEJBeVhXdDhjTzRuVFpYLzgKLS0tIHpkV3J2RkVHS3NWdFpvRXlqY1h4
            OXN5cklnbWh6b2tnRTlaUU1jb1hTdE0KAymKKWsuUcWlaPinW/4SW8/PgqTx2Iok
            GhJTBZeI5RQkF/R8GttcUkZ9AW7oq6NERPtCDdJMgddxA6PSCr6fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T04:12:31Z"
    mac: ENC[AES256_GCM,data:tWs6OFrTpLf322NgFBnopwfXI78Mx0T1arhlihAo6qvf9/2SFj5taL+HmUWgglG1W3htpL8uxr2ob3SfbsWrkW6RzKoYJV5leieiRrJqBzXQVA7uPj6I1qFT/VAQyVnPvBTej4uF7B8muYqlqqs552n9yQ58wDdlM1iSNGW8tOQ=,iv:+RicMcc4OArXjriSpgPu++5laxq5jZquvkjSVt7iyFo=,tag:OpY09uqWQPWYEXT40Z1L6A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
