kind: Secret
ansible_user: ENC[AES256_GCM,data:ccUAocY0xe0=,iv:k8xB4MG8pt5ShEgJRXm9Lh3Z06ljueLcKPmytFjMC7I=,tag:ciK75r4CxCc01KkP2VWMBA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DYpB0HoLjA==,iv:K1hjkQsHs5H2IxEJbmir1aenPHQT9J76BfPEqvf1NgY=,tag:Ppq63r8L8FEW6lQUJ+MO6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTTBMa0tlckxBMlROLzlx
            YnU2bGtvNWZudmhLZTV0QllPY3lXczR0SXg0ClB5VGQxUURsNE1UeVZFWVh2dEVP
            MXRLSG91REhSbU9LRzRoTHl4MTRDdkEKLS0tIHhBVnJoSnBxS1R1by9CSTlGVkdP
            a3RVaTltVXVNTTg3MFF2Q25kayt3QTAKp/mrOn3xNYTagm4L1Mn5ivLNYzvmvfoV
            uOb+qYQWpa1O+bKoz81n82r3tfx64Tme5uZnX7PqH4NP0XINSC9iJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T23:24:58Z"
    mac: ENC[AES256_GCM,data:lPmlm4Ocqj7qGVkRy/6hZHUdHrHV/EyrtQl/JPXenSfCs0nGr8dNkrI7o0pnPCnKaSAWPgpAX/b66LOzRu1xidl2KKKKr8ApmfQD1NbaXaq/S5ZvgmpedwClVneoWVnTT4DFkhaXWpw6imW1E6YbLePr/vMSX7r/xDSZsX+k9gE=,iv:ujjx0odV55v0Ht+JA4EN4wQYipwsee8/Qnoh7R4mVxQ=,tag:IfiAqiGUZ2sNZ5dKz48bgA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
