kind: Secret
ansible_user: ENC[AES256_GCM,data:dHYy9RTHbko=,iv:tAt1iKwgyOlMo/6X1t4Y3WTLzEv0memLN/1WV3gxBbs=,tag:5pGunElU5pfSgE20nNlZXA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9GPrx9aUfg==,iv:5xMMp573B4oV4hIsak5ReLcTbuK+UhnNNtIsf0RErE0=,tag:BiIJICMn46f+6sceCSpOGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN3ZNQWNKbjAvOGZzdEk2
            K0xVeFd6RWFpQndSeGh5aFZMMVZRVGQzQUVzCmtLZEFCdlFYdnFJQWh6ZnRuMXkr
            V25Zbi9mellSeFo4dkVkaUNZMWhwUGsKLS0tIHRRN3kwUllOVThLelV6N2xYaFdF
            YXRROEdLanRxNlhNVG81bU45ekprU0kK1RKNZQYEVcQqDQFZVW7a6bBZixFsY6zB
            WznEnFyqDqSPpGwdwj7KF/P/XbyW4N+oXZivYKlNOrz1VnQt2XND2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T19:59:28Z"
    mac: ENC[AES256_GCM,data:+E7b9V1pDxZkqdnX3Ukw3+gW3mmSj7OHz0fAIEOXXVzbPvdyKMRBJzTc3z1QDk1GbDjtjLhVjKBT/eJx9qmfu0oiAKRG+Hr53XGNjolsQpwAH+V9WupWppV8SWNB6WA0bTfzmH4nO3uZ2UfWkLl+2N7FE3i/Sfgj8VYLlJM0dII=,iv:j7YLtPbGq9BcqilG3/qhk03V66qns0GIgcleRBWqLbU=,tag:NRQUeChcqhjsuEn6Pz5ACg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
