kind: Secret
ansible_user: ENC[AES256_GCM,data:tbkdpMnjBrE=,iv:SPvp00CGM2ruWT+UDTkdZub4dz7jrRjfXNwkcCJABFc=,tag:kc0spLrh1qWm+OZFKQ+eqw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:K8MCNxM/HA==,iv:J0YKhIMSZTCfUUNtkogrjB+TD7HzcEc3WUZnboWhXRk=,tag:WNMZ9J3CMTAHr+fb1VhR8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdTViUzFLWnhLc1JRMkdB
            YkdIdE9CTUhmdmpQZDB6dHVGVk5rNCtsUlhnCmxaTGYxOWlVU3paSkg1NGhTSUx2
            YWlDT3JUblZOTFN2UDF3WU50M0tWYm8KLS0tIGxMemlxWVM2MlYzTC9JVVNhaThz
            aEEwbHNRaTJlT2EzbDdOellGbmNkNjQKVOvV3oELMunVYDgIYof3fJmM1krInYuR
            CxpJC4u+M1/OFMvscirsMqzT3PjpjLK84Kv4YoKwCGZSVr81601gUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T14:59:51Z"
    mac: ENC[AES256_GCM,data:TwTzipo3S8GTinfk1+71sL8PV/xa9pYbTQSKmqsZOjhHwQptmoAerfjBBx7E1AGqbxPV4SGcUZd7iU/JSoEjQLCVWccfhJF/dXkVTRiE9KugCjLaQeBcmwwx0y+tJJbVz7Exjipjg6we1vFvKhfjWvnTzqd5i/tvhVnCcJ/2zBY=,iv:bsrQPoqbKrqb/EJnAxEzepWpASJx/y4/nU5Z7BWu1Xw=,tag:2vZvEfTYpcMXHLDN4SbJnQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
