kind: Secret
ansible_user: ENC[AES256_GCM,data:yXsp+8bKrxU=,iv:b2h8y2POQI0L49afTqJqEqKE77PExUDDc26+tIaxnOc=,tag:JWxYPTkxFviAMCcjSAcWEw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:09h+bxOKhw==,iv:o68WVKx1DCfNBr8YebYQYxxLPG0jkHjQWHn1DVxJ+yU=,tag:ynY7dVSJZB+NzJ7JAZ2vcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZEpWU1VOVmxNWXdmQTFy
            VWxxaXM3VHpPL1VGY2NtSzdyYU9UTTdCMVhnCi9nT3JnbjByK2Y1MStnY2w1dm1r
            T3FMVEEyVEVCOWhZMkwrRERkemxWNVEKLS0tIEgvN1JOT2pONVBVYjNySDVkejhT
            d3M3VDlSQXNvSElEelFNbUVCUVVCS2cKcprY62wMhic59ZNfM2Rm1256yoEH4TFd
            n+CKHYbjaNgQGgBrm4UYFeFZLOKTFTPzyfC1Q7Wh7/pe13bRd8nTow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T17:26:33Z"
    mac: ENC[AES256_GCM,data:Dhdpc43XfJwFHXwiOV8cttMjaLgzcaAZbfR0w62trQKagoL9QFWRhT9rLmjCOo8Z8YcukdlWOpYy3H1n/jio4Qh+x434dzUJDLOWU5Gz+s6ra2nSy6beMhpqzRW96gJEzTBU1v8XHPhDdtlTKXnA3B/7Kh8ILnXtoD82R4l0vnU=,iv:RW6A3A7ly5R5Jp/GkGdZUfltyaA7S76lAzc/XyGwsnY=,tag:InUN01p6zp2Tg50mql8Vfg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
