kind: Secret
ansible_user: ENC[AES256_GCM,data:CKjXUon2Iwc=,iv:8E+egMMf5zY7df/xUoxdmm1A6Fjr+ZGcTAkB6xMgjiE=,tag:sQ8ngkMzSuIChV2GXaq5CQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ktVIiElSVg==,iv:2DhAmYSi0L3h+Msd6sylH/4a5mpcxMJ48qaW0KoVeQo=,tag:Acunlxi2v9P03KlSqczr4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NXNaZHJpZEVVVzVFVmJC
            OGtpeG5ocWlvWUZjNWE1YkUzRDJVakVxZUdFCmxmWmFEdHZmMzBRd0k0QVBxWEdD
            bytkbEQvcTRBOHlBYmoyNEJ4MlU5SU0KLS0tIFN1YjJrc3d0TS8yQ0Eyb3A2a1JU
            bktTOVY5dHZvakt3TmtWWjdGM2EwTlEKbxgeFRhJGGMlQwk66AtOckhN0pD/2215
            hAAFvaVMtltplqWejj6chc/jQp1Nhhrx2hgC9JpHc4dxAMcTx0igog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T19:59:28Z"
    mac: ENC[AES256_GCM,data:UMUfrZiw4nLJfV4WNZWQfvsWBuBCnTwdW/Xk+jeFew1ENGrSZanhiBTJRihjdpfWTf/ToMYX2tPfirF2nm1Wfcot0fMqsqDqJPhKi7oTrEehKe48FSSJA0bj8ceFf5li9Bk/AgmNwixyXkEKv3iyAHJe/zJx7LNtJ/Yx71k7Ark=,iv:Rd7fVweZkQpEqUfPIVSthqFUT/5M0BK4MhhAVzwKOfg=,tag:Cpwqsu1nXl4vz9p90Li1ZA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
