kind: Secret
ansible_user: ENC[AES256_GCM,data:xlpXWHSZRjY=,iv:TH+gHWWSsHMgLLDvja5fYHI6i3nt+7auo56jJX2MCfY=,tag:MxhuMyK2PQymshUkFlnXcQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:T/mxhvRCsg==,iv:A9wRMazmmV//ZCGLB4d+lPnBVrl0H6Zz/WhSh9U0NrQ=,tag:AHig5KqNS+oIc7Q6RQooeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTHhqTStDNEtlQ3hvaktF
            djUvSW5Bejdkbk5rdGQ5RTMyeWk1dmtmZlFnCklMTkw2UzBKOVFmQzg0SGwxOHpk
            ancwcFd2Tm1pa3pWMWJJd2J3VWIvZGMKLS0tIFd3cTh5L1VENmZ4aUMxTTFZM2Ur
            dVBJRUV4UXNlaVgrRGJtSjFiajZBRW8KdwDLwv4Kn0ReXMutmbE8dzit1g5ksOVI
            7JSn7w3KkjmP38jGoj9ryZiL9wNWbzbns7kUttx7YPJI4NVHfwvgyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T22:16:04Z"
    mac: ENC[AES256_GCM,data:LjwObcH+sEPf9A93tnKnWi40oo9Zmz5WXQkduE/7K4+LIgM/F1ohNWTmQKnhPZ+YgrXJi55at2uYfqKw6NTriDdjSz40CA+VCbT7CLohUr/KJQZbC5YCWDmBOmmwrQltDBkCCErHAhESRt3wyLe5/lRZ0C4TF8VETjylMP8wT7U=,iv:iQ5BycFIqDuOgDLenyAG3H3izNxHoZEXHaBqqD3alNE=,tag:SQ8hLE+g7JyRAel3biAKqg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
