kind: Secret
ansible_user: ENC[AES256_GCM,data:+5nSoST9Ks0=,iv:mpsc5zUl9tPoreEEK8VjqHuPrX+mGSuYcqSuQ4wZ0CM=,tag:Xp5BkB7bOM/bsk5W1Uxb5w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XvgjiyQ7kg==,iv:7yTmHtHicHO4PZIi9TRGrVtKgZ+R4ZjU7gZfKUte4oA=,tag:bb27Bb+T4VVnjUCDUJyN7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeEZQMlNPUUZLdjZ3T3J4
            OVVUeWxudVJhZGc4enZsN29SellJQytVOWljCnU1bTBMOEZqMmE4ekVqSnN0ZVIy
            N29QazFiRVJpb0d6YTNIdmJDSktEQjgKLS0tIG9PSlhqaFpuRy9GY1ZGVXBCekE2
            aWxJWEtiMERwNlI3YTVpaFpVS3lnbTAKK7SXD+UjL4gD+GWyOBFLPT26cPs5A8sG
            6Aoei+Ebpvdhw8Bnkq0jIyjX62AjClEsK+xJiswrpn8F6X2pLU3RiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T14:59:51Z"
    mac: ENC[AES256_GCM,data:eJvkhKoiuKHqAhfigoBY/qfF55I/xypbyEziJC5K/2/Isk7DJBlR8OyuEoE767zjgk3vncD7XHCqxHXMgS39Ic+1VeVPIA6JOg4vf8eVbXc2fWnTuZjW4Ig1Fshxx8zMjjjaf+IzTsNkiZlndnrxC24+XyQITHgTC+GSco4n/lg=,iv:ffKgZLZ2vEN9ExnW/BFIRXPuAVRKWTZ3XPI0hmCdtbY=,tag:R+OoIr6PCm+do9Gb1CARXw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
