kind: Secret
ansible_user: ENC[AES256_GCM,data:L9X8n9HwrWQ=,iv:phdEKfk1oCE8d/V/tRuIGCdzgl2ZpCYrNJ1CczCca8A=,tag:r1mjfpKPkNj21E80919itA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:adrubxz4EA==,iv:wU7Ta/h0WzbkhNopxrAyHrjEuKJDip33IgL8Rg3mrp8=,tag:UOf4P5k5oDVrgAgEZ5rJ6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUjNXUTI2Qzk3K3NQc2Yz
            bHdZc04wWkZWYjJDS1hNTnRrWjN0Y2dzOUNvCjhCeFNaa2JFVXRtdlR5NXptR3RC
            Q1ZrQk9ycys2TnNZMWx4QlNyWHVncFkKLS0tIFdwRDU5dWc4cVd4dkdKNVpDTFhp
            Wi9YU1JDV0h5K3lYWklHK2JlUXYrb2MKG5nv0qB9c3WAiJs11dWAjjuO+0DEf39S
            TBPGokmgXnZWkohJr3VAaMBJDVQ9FPGA9OgGPU0k5z8xAp7hYp3JPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T04:49:15Z"
    mac: ENC[AES256_GCM,data:ueQmfrpwpvcKJ41uzhQ5v7VDbLwFHf+AgFUXH8Svktb9HTPe1sZUw20taGrlzoRhYZW+YKhjdz/mg2+yjYIvizKz7wtcHIOj5gybwd9eJHTH444TSVzqpttOre/xRF26ZW5X2m/qiWy0gJaVEl9y605oS9itFuJacBy6kEI8i0w=,iv:DfJ8nPoIjFqOr3N2b7EbaRBiZo+orYmcLibJ51JzH7E=,tag:zTll1J49dLiHfjHB7H2vvw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
