kind: Secret
ansible_user: ENC[AES256_GCM,data:l/TlGjtTma4=,iv:T3A1QnoLgrEAhELN93PyCBmJcb3LljQQ/c05fZ28rJc=,tag:yPKw7cvzcBoOPg3yYBtAwQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WhVPtmSHzg==,iv:ukWkqzC6krMoMcmU8cQkFwI481CG9HpEB2JyVVMaERs=,tag:ETXOA4majqeue/maA9RuBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTllsZ3FqRjBwOVhQSW0v
            MHhCVzlkU05mTWpESDNDSjRGY1NVWTJwSHhnCnR3cno0bU9SN3d1WGZDdFVnUHRK
            UlVuc2hZdmJhcGZ4MDBaR3Z3TG9RMGcKLS0tIDd5a0hXMmZ3YmN1TCs2VklMTXBM
            M3E3TjVuWWdTL0pwU2NKZUgzSDRmbHMKRM3MZy8nJwXxP30Jo15PiGw7fZdMSgcx
            DyrdjbU2lUOin5yelSzOanqhTIM/2p8qe3sWjXEn4S9tnfcpD4h9JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T00:54:35Z"
    mac: ENC[AES256_GCM,data:1VzAXiSDFxIyJdrMeQb89jTHdyOuq5zrif031+rBjoNiihG9dP+7H4GjAxMtTsuQYJIxLRlcXPV3izqnHX0rUhu+IhDflACkIrFhcole41iE2NsDjkoFLBdkVSKU8/OCBLi4zAd+pGhmwCPpq4EU2H7TC0GF9PfuugZmkAt5Xc4=,iv:e2GS2SqTh9q2diwKiNx0ea9h7sWy+A7H6jm78185Blg=,tag:tBgl8D8ugyvCrGJ705gxrQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
