kind: Secret
ansible_user: ENC[AES256_GCM,data:VKjc+ycnpq8=,iv:LbvILVcLaDz3x3OwwN2NLVNjfKvwWRUNtLncYHTmy0Y=,tag:nLz8H4VawdC9h3GHsQcI2Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:R8LUoSUYYw==,iv:lKqvHf2g/ppfeMtzzn5I3McDMvv2AjGJ/he/uBG893Y=,tag:ZKxXbwaX2/dppc1GhdLCCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeGZ0UnlJbTVSTVFLbFBj
            OHFNa0JuU3BLVXFpKzJlNFNFUGFFbVlyUEZnCkJKWDdKNFpsemRMTXFnU0NoVG5Y
            bzNEaFIzS0Erd0hZd28wdWtTNHZaTE0KLS0tIHM5YjZ1ckR2cmV3ZHF4c0dqQ1lT
            NWREYUZFcjBrNnFULzVWcGpUM2loQVkK7Xutuj4WWhI7sSYGOOUHh+15xGGntZRt
            PVOXup4HSRFPLItMO2IWFUcTRJpL3O4sT22Hdc5sAPiKyI1jgSwtGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T23:03:25Z"
    mac: ENC[AES256_GCM,data:csvGROTjxjLUwAGcHIe2hdqdhtUFx3fJOgSvwQQx9wcRc5FXucvZr0guVE/LAnxsyWMYHoXLaUX2gB+2UypxoD2jreMkAhHG/Nzb1jBpDDlwtEMCOU2OItvmI2Mh26VN9zgfGIVzIF6m89fh1PXZQOPC3qtDQCpYO3D2dAdAk3c=,iv:qqPAQweSETEApzGrNPvYm7vVFFmC72CCkG0Pg4CYOTw=,tag:oSWgpdn9stnuCZpI+Hopow==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
