kind: Secret
ansible_user: ENC[AES256_GCM,data:LAH+TGqzsJU=,iv:YgELYhRLG6QHLZuC21oa+1xinN1kN+QVbFuyiqslTEc=,tag:q1DxO8psNkn4EFWtsf+e1g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XpwJW0GmRQ==,iv:G8O6yG6S4Xe2NtyVzAp17vdB+TecmR1ebcrVSKfBSZA=,tag:7hgxtIW+pld1NdIwOSPU0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WnE2clhqeXpPcElId000
            TFRxTDcyYTYwSFE4VFYrencyUWw4aHZOdWlJClRmVVBPN2taSC9XdjRwbjhaMjNI
            S2x5MGhPalBaRzhwUGpMS0hoRXNSYmsKLS0tIGE4UEtxYXNBVy8zeVUwK2xsNkM3
            RUw5eUlreG0zdGhqdTY3dG55RkJHTzQKOirn6aIJfVoAULgN9uEKySlrf4Zgl6za
            PyuAqhN85GbaZCK8gCySyL5lr36lLZTBb/eEAq0yPTnoKVOibZJJKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T19:15:27Z"
    mac: ENC[AES256_GCM,data:SedPeSyTcG7Xepa0tZ+Qx9vgS2vLQMkq9CjR1PZqWb5vIDVNZuSms0yTFNH791T9DcPS68m3bFbcAUkyb19SKY9PURq4Rh9kPcTxI5am8ojIVS+v7aJcjPlKgIinzq76ORW8nFldEKT1TWi7d/Bi7KM56LFi5L8kEIpJ2ESKUQE=,iv:cusd1nKAzZZEIQZOwmDx2V+8ufFoX/T0uPcMZhtRezk=,tag:FHsmE3Ngb09WKscI0WQ/tw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
