kind: Secret
ansible_user: ENC[AES256_GCM,data:RX38+RQBykA=,iv:cDNnuuBSnpIO/Z6u5s2j6a6mXEcJQB5RG8Ow4Ta11Ow=,tag:s/rBywmZVjJsA5wurXfctw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:etDZ7IzXkg==,iv:T7CGIfqtin9rBqxq2Dhzy+OlMCzu8vqSDyMEMyRVyPE=,tag:DXw3Slwp6bMBNfG4ehqXUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL0hOZDJhcVMyVkRyd1JE
            cVZOQk9JeHl1NjdEckY1ajVocXNjdkVLbkFzCmRXVWtyczJ4VExyQmhnRk9Hb2Jx
            NXFvYUVIUzhrdGpyUHUyQ1dJWEZOMlkKLS0tIEFOMklSZ2lKREs0Wlc1RHQwL3Y5
            T2hJSjdScSt4Q043VjBJOGFBbzNPZVkKgyD1rCAoGRuurVzzv5b5exdjJ2g/3tKE
            vi6q+UWPtdRd6h9xCLzm10eaSOUZb5r/tpi2TjJ6qq9z5Ijlh2498w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T04:49:15Z"
    mac: ENC[AES256_GCM,data:geLuZfZJvd5cMaPFB3S7O8aWmbckRqPRkyVQD1ChHdWQKuQrvifpkSvszyFK+83gv7hoij7UHCg+jOOTZ2h4cNwGJzXEkBxwzi2Pxfwpvf+1V1gCbutCZPJH6bZTWbQlhaI4vjXQTZXdCPCGumWUcCATv21+2LOOHSfV0RU2cn8=,iv:0huk2aSDWFWVPHkOSbBh9tn0ZLhdJBKBc8lzooJFQHk=,tag:BP2PJmLtnSUme7S9fy3IMg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
