kind: Secret
ansible_user: ENC[AES256_GCM,data:rKrUeP4i+tU=,iv:iuFhp2w47V1IRKPA+ePVYZUTKlqnWkNT/oxZbYf7YBo=,tag:PJ77bUdfL/oC3jWBTIvLag==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:bdT8OoaJzw==,iv:smBd2h4hPoK47wdv4yfU2xHSN8+Wrzhqj9ZePhYzisk=,tag:DxyTm+Hir5RyYunlSJgvsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MzJhVUEwcmlDRjZ1aTJN
            eFNSeUZSR2dqN0l2RVJPaTFwa0ZHcTZacGxFCjJrVDd2Rm5YSWFzN1hzNXlpQlVz
            RXdJdzhVYW5kU0F0TjU1eWQzdDRDNU0KLS0tIEhFL001bUw1OGgzKzBMT1lNVUh3
            UG5pc2JjTTJoKzlXOXZlT3kwSGxJRmcK2dRsuhnxRLS9xnIKXiWBZ90ByAXJwSXW
            XfXkRmZTMi8N2AFGInFoH9wJv9boivJ0NmPfxk0J5Q41yMnAuE07aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T19:15:27Z"
    mac: ENC[AES256_GCM,data:KBvav7RNcFQ7ZOvv6BXA4kz9VGB2Ijs/VXGLBaM+banHLKt7nPOWbNkoYYgh2Hi43D7yUpdnQ7wuMX6nwRvh0ygspFDvmPT5j3MbQy1X2Lbzb0lZWimCYlFgGE5Voi7L5PiXSc+iV/FjevZOKiOUGIP6477HNFOlnyG4EnPlD+A=,iv:1qujj8+fvEwX74PlzBDJAzffLZpeVJit1/3FzLAhoCc=,tag:tly2h2Ljv7+YcocKj7vviQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
