kind: Secret
ansible_user: ENC[AES256_GCM,data:dNgfDhlETsU=,iv:gHkvBZ6h5GQN79H5tV8E5Xce4gG66RWqSRG640/aW9o=,tag:s8YqtCdC2OIJGeMMTyGYUQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:URfT9iLiiA==,iv:V6dsdgu0BW5088fxDOgtvWr+Mf5NaVoPJLTi0pXw2h4=,tag:qqUEDdg8Sv0RV3EKC7bDag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcG1Nc1B0UU1WN1lrcmNi
            bHlyNTJhTWQzSDVsZ3R0Skczc2dKQi9kSUNRCnZURVM1d0lJdGhSZ0pHUWorVEE5
            MnR0dXAyaEYzYlRDakgvUFNWa2QrS00KLS0tIFY4VVVnSmVtRWxLS0lScjRuR2tr
            UmV0QzUrRVFGVlhxU29TVi9yT3pCZlEKZu/8VMeOjLlt2pfSkW19kc2xcGJJBJTp
            6Z8hIBwM2EoJifADQSekm3RuTcxk0pc9kF7vyycoGeihHOLUdnsEvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-11T19:02:14Z"
    mac: ENC[AES256_GCM,data:Yv3A+h8Y/AwZLs7Zs2lwTztbcWJhRwNlirQTI8tsEqWo81FHCBKBa6Zt9Bx++V5Z++PDKFmLafaFjrvrzdwP+qTHac34/cu2M+oxqv89oB4aepSTObhJ/j5JOX3jG6sadhg1ddLeKNPsKMReK20uIIAmlqfKTAV2nEgw5FDuMVA=,iv:JLqlBlk6/JWZwF22k8bHSBE5oXBL2AUNvgjcesP/Rho=,tag:Ow6+V3tfOpOrQ53YWfps3w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
