kind: Secret
ansible_user: ENC[AES256_GCM,data:ccVxOr0r0Lc=,iv:rXr5z3NEj6EU4YgAaYZAi0GbsdAXB8xEcJ4gm3q6JHo=,tag:gYyzEwGX82w4PFL5QLh2rg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0UqhjtWByA==,iv:IYO52c3qo9keyRU9AITEb3RtkaXizRZPSIwmDM7WZVg=,tag:wRQIUqFWKU9nTgYA5cpLOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZkhGUTRVY3MvV3oxdDk4
            dGNjSitDbE45bjIzYlU1YmhvN0hpN2o4WEZNCmRXQWZFaURwTEIwZWdTSzNYVjY5
            ZjFYaXh5Q2xVczQ2blhIQVpNY2U0RGsKLS0tIEhwNkVsUUpKY0JGVDhNY0JRNWoz
            NkJCbURKYmxoanNHVWpwOEtEaXNtd3cK3Ye1H9I09FsuoPWZHkne9JyHNTtZlTil
            AOPb7pSmLH3kotPHSaqQWwc4k4npeCHIJ03dDmRCqyd7mKCJYYlX+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-12T00:32:51Z"
    mac: ENC[AES256_GCM,data:pmSxi9MPy1FPpQGcKYxkrBqy6CATFnq/BSSfgBoqytVk0eIfKHxBPrlCwsC6gDwalAQ3VvERoe8LlU+HRLGQItrS9yymyWJOrwB/48waDPBSRN9kpyOGDspPo04LxZhN4Rg5/otFvjFdSPonVcuvuxn2znwBGFh6JpY0C3vF5Wk=,iv:SOQnTaCKUdyMRpXhu2BAh2oI3lWzS2SaWLNwOE7/wNQ=,tag:SNwT3Bxgdq3iPNdZ2OOJDA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
