# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ib0yt71wdzSNB8wP7w==,iv:pPsEpahqODP/ZAm2qvaFQWP5WlgdStk5YkqjhV9pAXE=,tag:3MIidV+XEzWF5nWK7cYErA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2RGujlaW+MGhUAFuWuMOrYDTlpoB,iv:tkVY55ISHFKCWqXsjMbwDrTOUlNxwMLk4EanninPpIs=,tag:KjDw4OUJo5hr3qSSilPo5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBham4rWEoxcEpuZnhUemRv
            U1FQWk1hejlsYllOekprdDNCMHBaZm9ZNDFVCnA1a2tieW9zZ3hNZnlqZEVyWkZ1
            SEdWd0xaZ3RTSndCTzZVMGp6OXd2WlEKLS0tIE01eWNIRXpYbERYZGZYakU4V2la
            bjlHZWFabEpzSHowaUI2TU9VTmw1bVkKEmmTtcFPZjofmrC/SxCYtzS/dad1O6ex
            XaL6Shs81kHTBb/Qqm2fpXcQ7m5eUcRTxIujjEVas841eFr8Lram4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T17:26:33Z"
    mac: ENC[AES256_GCM,data:sCkiAzG9spwtyE3G2jdu1/oHRspcpynURAq0qvs+MmieX89t/BPcuXdJZq8pDI3gYJZgggDZR/ar4/rDR0ak7GP66fTxsMuAlNFo6efVOyspYY8HsAN/9Mg7KCs01NYx2k2QoyPuMP9LPq9R36zZBn/XSeUm9De6YShCaGrOACA=,iv:ZE/se91AwdcGrFrv0QKGTV0oTw3FgeFSr4ah1F3a+3Y=,tag:TmIApS9wp+G6OWa1FgEmfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
