# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lI/CSUi3/+JI5OJJFA==,iv:93jWuLYiA8kyqo0VWo/xMWK+J01joysKlqIUk53q8yc=,tag:BtMKFSvD++J0yFHzw0DzyQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:g9Fx/td2qJzKI2cGXfW+nbdhaBLl,iv:qX6kvvR2qlP7yulDuhhYNEtuum/8pUuYLKvdqq5I6ys=,tag:hZgCNtmVsD4xHda8Jp/+Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMjhKbkczMTlPcER6RFlE
            QWtkTmg5REZqVmFsVElBZHhSYWZ4eW1BOTNJCjZxV3VzdnAxSUFsZXVhazA5TThY
            SGdLdDFIdUNlSmtHcHRtdXROM3N5U28KLS0tIEZaUFhNaisvcEorcVc3cld5L05H
            TDhGVWVmaHVXQmV5bVRwNFZ0OFdJYW8KVGCYQ6ygkHKm9bvy0yoQ4DFSBkfkIC8p
            XoNeg7cK+AWxRKc1Gt7FzittZ6cRomde2ndovQZxIES3BLwTTtucOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-13T20:13:29Z"
    mac: ENC[AES256_GCM,data:PQKS9QiNE7Dad7t9u6vibqDe411yvvndHscCO47c0SJ/6+mLAy38i8oe4u7C3sSZsLGXYZj6tVoDHfN2rTLQs4r5x8SkPEZ/sQpaxYf0pBXa+PXS0zDHHai5fxgDCOZtf2fYZ3YLa2X0u/M1enaPobEdTT84mM1lx0BGWvIKVz0=,iv:E/u9am4QNFACjrcapDR2WCENjsqc4H8QJQ/ji4RuvDk=,tag:knf5BJAJLsv9EevNppCYmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
