# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:YDRC/qiLm1FkRllU8Q==,iv:4KCs3eZX7MjUErmOh6PV4EXXlmEp6m3AlB9WbDX3Yy4=,tag:5UslZ8Yuka+RvahneJnCnw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+4mB8y/vu+Sd1ssOqsZIQvllrdbj,iv:FNdST+l31M7qbR9+v/2PKiOtFbYWgYiScNn+yc1AyKc=,tag:kgpG5UZ+lpWqs94D1WMp5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUVBHZHdqeXgvVGZPeHh0
            TmYxTmVsTHpRTDZQY2NEaGx0OHkwdkNldm5VCmJIMHBPYWg4VmRtRU4xbzlxdnVP
            QXR1bWI4WTNMbU5FRDhKT2VrYXB3ZjAKLS0tIFh1bmFqbmJKL05SRTRhOVZidHVi
            NmhXR2dIc0JtWDY0MzNYYWs1RVg3ZGsK0PVQ1Kuo53DPQtcPem+mvNKZDXl9rvaX
            +dYMFM7PoLVmnJKNxUfpg9HkIcmElutvCoNOMK7tmBnhkcN/3AklZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T04:12:31Z"
    mac: ENC[AES256_GCM,data:dgA/UBBHrEGNTEevDzwUPajQAI9DBQ9EsqYKX8Vdh9CqUv9hdbrbVvjePHgxvWWfcIYzhJPkwa8PA3qYU3fgdxnHwmqsxGjAgYXLGU4/CE7txt+fQB3yAIHlQ0Nog1ZbJSJwj5sayg1eOW92Mdq7kLxM1iTdd8QbsalPhTRYOI4=,iv:r+IgQM6MgC/XpGMCQqdetko0sXaoXSncRPIw4n9O3so=,tag:BO3GbuEaNrCtSNAEOkVsvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
