---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.1.220-10.0.1.230
  METALLB_K8S_GATEWAY_ADDR: 10.0.1.220
  METALLB_TRAEFIK_ADDR: 10.0.1.221
  NFS_ADDR: 10.0.3.1
  LETSENCRYPT_ISSUER: letsencrypt-staging
