---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: db
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      version: 11.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    clusterDomain: ${SECRET_DOMAIN}
    auth:
      existingSecret: mariadb-secret
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
