# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9IW0btw1D61Dg9BP5eSefXFA8Rg3xaR+r0A8W4JARfcOCu9YT7A57k8TLeD99zTl5xXVYwSc9ZM4VV+UEZLEiXHnX/a5a994V08gIphuzQsASboUvCgXQu6OP848AgKGxziV+qu67OCCCohlAkYYbpMiYp8nnYFS6PSo,iv:k1t3wgs9tUUyJPvG3WMENuJis07XFCXnQtdF9wMGCAQ=,tag:qQvf1Uv5diUkJ2yD5NOOkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a0hDdTF2VmN6dW1mS0p2
            c0RaQldJdmpadEY2VWJUaktSYllhVXZRWEFNCnVYY2JIREdFRzduM2ZDSGhJWWJw
            VW4xcjBXalFqRHZ5ODNpRXZpUWVwRGsKLS0tIEcyOHVINEZtdDFkSURzS1ZXTjFG
            NnBsWXptU2hVbGtBY2s4ektleSszcXMKl6WtvQ1RuDldQDGCpFli2O/toYdA55mH
            CiWTX1MIskYnOaVraXEcaJJzWPeAnqzEjUXmAfRsKnq2nuBkR24+oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T00:00:23Z"
    mac: ENC[AES256_GCM,data:sZCdkDyPKftjM8hL0FK11UHFhS+Zlqiw6dMZ6232xre2CQbnY58Sdhhx38mDGchdTB9EBJHV18JtK7BRok+LnTFibyfqsN2b8ftsLoOnZe8YNY4tOj9qbcXofFT++GyCh8GADcTc6tMKEAh0DwWmnOenPVrcNUoS8NyAO5QHLdw=,iv:wWLG04ULrKvNoQSfDQBcfORLqHYq/4MHXSUZ1S0of/Y=,tag:2o0wmNiOyPRBREEBfKN6sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
