# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ntpLJV7cGP4IS/04xC1pW1rEBJwgbInMAYPFIOgGX0uBPxQPeKBFfJu2z0k2/lGIKmVY4rTgrgXYyCZ6sE83qjMTDj0x4nAFz+Q+VJ15v0BUNLQzaTuSGJO0C+zTUZk1x0RvzNS/qFokwAu2Z8qAFSwfdummomA7DLqH,iv:qediNyzgQ54AfEerj7CHvr/Gs16RNhTG8lZkmRH85k0=,tag:5FoFrqGnNiX13Ffns+ZgCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdFJUalNHZ3ZXSFFCWHJE
            UjZZWGlFUDN5ZFZEL2tYcDdWZWQxMndvOG1rCkRVUVJicmJmUkEzR2JKMWtLVUpF
            QWtxNzNSekVibkNjRGErcytlNHY4MkUKLS0tIHlKcm1rV091VktSYWJueUM2bFZ6
            a0x5RnNERDZLWWhob05sK3pMUEwrZ28KE+Y83LUBLom/glViySTkHE6i7vW60ZA/
            1ERsoxV1uz/MYUQ8n21AqCWqXCfEUhoJz2hG51TCmmHmKifu2J2ygg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T22:16:04Z"
    mac: ENC[AES256_GCM,data:y/hV37ogsxqGzok9nj+JhhEC7bKHRjjSz/IJK5smbsmJ0klSzSA9VWJ33slcl2SQOwqIuX9fBvJiO/skdUU889cqecDsWJwaoERkVSNhBbpA326RqFBzzmiTVwBX6BhWBRPwFBelkF8Zf8CoBfcpR2ilmWki1JYKrEC9W/Y9vBU=,iv:C96Hi2g2Ty+o4UvHWckzXr5pOmJ+wivh5X700F5Gkbg=,tag:kl96O5pmIqckGKmAUakC1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
