# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hPphssrsr7BHE+Hl2sgMnoFcJYYsI2SFkCyYsdF6uAUn/vaZv7X9Lg/cUYnuy6OPk6J6hAZIsnfwrqvSBF+FCyndPIA32AC3/YTmKE4Zz10v4PzLQVHOStetn6g8B9p9o3XrQN3AyhfEugGCrnVZR+GUpiYKVqAGdAeE,iv:VwC2x45ntMX9AwJPyfIjDXsnZNI8aiZZz17U7IvezVY=,tag:T1IerqVnLuK99qxP23VDXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdXhJcXJ5dkRCUHJKbVhl
            TW4wMlZxSTYxUXg3R1Fycyt0YmR5VDdVNVZZCnBEeWZoOFkvQ3g1d2t5RkMvSkNT
            NjY4RHpJWk5YRWcxSFpWYU9ld2VZNFUKLS0tIHV1cjRrMzdRVi9XY3I1Q1cxWjRJ
            b1l3bXVPeGxFS2N5SWFHbk5yd0xTb3cKKGP/ki1NvGZfKSQG5pmXsQ8Tujih05b+
            AorZPiOUFQ5RrWDCyMZj2wXbldYh66rwrX6unelsiMGjaUXecPVnvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T17:26:33Z"
    mac: ENC[AES256_GCM,data:VHsYlwDq15vAEFODWnSRrHmwv2c9/2c2cjX8hYvqCHpefNC2VAzomW8VGX1CwoUd7QwGeuLmt6sVE0Rp/e46Tyv02o8GBG8tUtLzwCjXL6Iqrv5AqWXZZ/zVN1G43/XRtm67RvHiL0NIFxmrR0M308m1kyhl5ualievjO3Lll14=,iv:QE+HJi906qFWZzrB6u4nmtpmKZFjoBD60wIvzPbiTtQ=,tag:ytUxqp3OUfAmECxzA68DUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
