# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: db
stringData:
  mariadb-root-password: ${BOOTSTRAP_MARIADB_ROOT_PASSWORD}
  mariadb-password: ${BOOTSTRAP_MARIADB_ROOT_PASSWORD}
  mariadb-replication-password: ${BOOTSTRAP_MARIADB_ROOT_PASSWORD}
