# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bN/igPpfDyMdpwORzxxeKT9mkeSJL08aJaf0NKHnsTWc5dR3wA5TTg==,iv:l3MnoCenMigHj/FHgEdhhqZCug3yriwkdF6JivIuffg=,tag:uL0x6i6WUD+/qHsETbdC5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVEJEOVhPUmdDSFNlVWZu
            SWlUTDVSMjJxQ2RFL1haa3VWL2VhbDVLcEZjCjEwSWFYYlRNWktpeEZGeExhY2xL
            aFBDaUdNeWFWK1lBeExDa3d2NkFrOXMKLS0tIG5rSy91NmxUQnZlNFM0SEU2K09N
            VXVnSmluY2RmZ0hVY0NoUmxWMUpOK28K6OnBC1fVLOXIUBFh1tNIjGVQnsD0gTQz
            M6XC2/hCa5ystj6QXFXprJpCkNK6jTRgPzBqHplrKdMj7QrryRwRAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T04:12:31Z"
    mac: ENC[AES256_GCM,data:1w9vurseeNEWOxEiEHYDn8foPy2XQXRTQgkCb4P4BVGATXE5GpVXGXPbsCAR7/fsDq2vkLZ03sXloELatySpSCNRzjSq7bNY/21iaJBiYl7vvrz/KLrFsBkaC+/FmaPv3JTY23DtfNrn7NuKK5qsoWRMATGYayqgK4/0qEXT1RM=,iv:9Kh/LKXz/TZlPahvBf30z5g4STzbxA9UGSYlYC8M4mU=,tag:r4Lsv/94/gYVY5mJEP++Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
