# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:z2My/k2gbLTheZ/19XDQM8r5vZPiJez8WxDUWP0m2/I86rB7iSwCng==,iv:i/F40RZsHgIzjKjZAdfKduAXZ1MC1bjldjStQX/4RmI=,tag:fhEoCzAWR/UiEyHq51hjLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRXhYR3haa0k4aEFzUnhu
            OWVxK1g4Qm9VVnAxdktqU1JWUnY0VVZRV3hFCmlSTXVVT1lHd3JpSk0vbmt4Rzdp
            NG5rQ2YyVDFqMnUzQU5BK0k0ZlJsQmcKLS0tIEozM240K0tyVytjSk0ybnM3S0Q5
            eGZERjl6TjRMdjFnR2djQWU2QjVSZTQKF8/u2eSDjHKVBjSmIjs6KKUSF86WzFOA
            gzIkunQAxh029g75aAuDbkQa38pOZvJIJSBP59TXRN74OMLjqEKB+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T19:15:27Z"
    mac: ENC[AES256_GCM,data:AfsLduDBtVImkYeg4qaQs1FWW1eeVOh9M+T2AvjchG6bJtvvXvZmTrUiB+ql6XYSSOsOlO/gCsVX4AHD0eZuh6yLMxS1y2aoOVOI+Hxv40ype6vWLJ52JRH+FNq+JWGWHtHv64WVBCgy/bgMOLa4gOP2vXcApgCnWZI52SfpxHo=,iv:oa5oV17Gqi4z2/u5rWjkUnb3bjFL5l8p2Ada3uy41GE=,tag:Qd93pyFM4yW7kZPeq3+3gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
