# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:f7urkj1on7yEEdi5Z9ruvsNtHT3rbsQWgONNwFkfrFYpM0Qurg==,iv:6EtolrpoAohIN7UzOlNIYpuoxcqp7yyLnzZlaAjwWKk=,tag:9CAhFKppV57jXLRlmVEu8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNzh4V3hGaC9VYk90cUVu
            VWtjTzcvbFE4dnpIWUNMbTVhWnFlaUxnOGlZCko2MHJSYklzNUNhREtTZjd2S2NV
            M2pueTgyTUh0bHFTM2Q3ZEoyZ3RlcWcKLS0tIFhuWG1rNVRBZWxRK1VlYW8zN3Js
            eXZxSGI2Y0kzUjEzMTZtd0FiTkh0aWMKwIRRuWl9tlZmtPc6LYBa19u40CNjyXNk
            4iP7bb8PNFz4+fYxWPYToD8Rx8EuqvBGHmDEuHdyl1v2VQhKAZ74Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T19:15:26Z"
    mac: ENC[AES256_GCM,data:hSYl5SaD6hFxBsoVnwOAmBJZ9U4vi/UvIype5tWubZ0g0eLwBtJwuDNrGUtSJoWyCewh2vmjxi6ba2+x9S+cHmJLlNyusn5eHHIfl98NreDFdJVBRdACUwnYSD1jVieDlk12hID/tRxj/Xe7HldcWw3Is1RgmdDvt65BXN45cOY=,iv:PAyuyG27w8e93oP4ELnAcz9vvM+wE9xVCUIH4YoWOHY=,tag:dPJgF1szl9RylaWlZpODEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
