# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:UE9doqeUuJIeU58KXjZcVPGdwu0jeeJ9q5buiZJnK2ksC/zrfQ==,iv:I454U800rsX8t5PuxORwYpAesKhAoZa0Wg+gKXvQgnQ=,tag:TffMcrlL6j9HFuiSKdRZkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWEhHTXRRR3lUMTF3WWdC
            bVg1OU5xU0RzbWxlWWo0L01qbmtubVhpSWd3CmFKVjZzNmpUSVd4Q3hnakFCV2V4
            ckEvNTBhWE5SbkJLamY4QTVXY01pZGMKLS0tIHRQVjAySWFZRDB6ZTVFOEs0R3ZX
            VEdJZUJHVkF1ZWxZWFVxcXhvUFozalUKYgVdZ7BP0yfnNc+HRY1pjmUMJPnvr1ui
            ckt59zLksgw0eEsXZBiVX+xYly12GvEhd0NIrtdxcx7nk+isE8zENQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T23:03:24Z"
    mac: ENC[AES256_GCM,data:90ZSrA3fcw9kn0NfFq5T2BJS72EWKCA0WJ4eZHbAjEMMausn9fwNbJY4lbHcSs7BgzbYXpTC4mP4O5eoyyUOGO+ksjcaDv3NfhbkRmkQ/rHBzacUlnSzfR7epKV8fRx5FgaxrJz21Ox6fo8WDJjhLrfSQuEuBn7cRmBDp0BIaYk=,iv:XWOS+7Z63X7vrBldbzkQFN1KIO0WEnisb0Up0kDSv7Y=,tag:lcXSTkKm91U8ev7kwLpUdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
