# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:QLEuoPkWh2ID+NmRY7WkhCi+ZUynncQd7ea0DDnUD7cTQz3PeQ==,iv:SAfFmeMWTqXzLA0Y+lWGHqWu8Ga6e3ngI7N3oOHD7Fw=,tag:F5W0ZVEe+47qZzeXl+++FA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MmtNd0pWVzNBNG41RDB2
            QkFCa29nZE05clFpekpzcE9jOWhrYTFhZEM0ClVxYkhVNm9OZmNaZDBxZ3I1WnFF
            SGY5VUtkVG5RUXZkeXcvcGFjK1pJeE0KLS0tIFR4QWhTdTRPZW5mcUhKY1RUbFBZ
            N2RQQVRVcTdUamVMeFlSMElsejZZSFEKUFSemc35d86G0KQt4EbFnrS0TOb35Dg0
            M6wSogT8DHUWsQlw1mdzAwbvWtfy8KGcBlxmCc1CU5BwLlRZ4cThqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T04:12:31Z"
    mac: ENC[AES256_GCM,data:+4vkvLBbLb5e12Gt066oQU/aVV7svEd6mhZErxnKtx4G0HsN/IeDOXB8Qvwq0OIjWhwYEdDbpfeK3+DivFDKgU9Jc0DAOKH5dVnTinHE9J0fj9RailEkWU+SevPFdTSPu4qX7L3jYgtv0G6i82wRJe1Ug1nm/LUeY+M0y0AI938=,iv:KsNlnoheVf2lmWtWIErSRrjGf75gBPDNY2p52Wkc2dE=,tag:fUDpjSlzVUk78CEMvVnfAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
