# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:okotPXW2g9IhPeA3oTO1YsF3WSFdsg9z7mdxHSjgxZutdheSfw==,iv:p7zj53Gh/aZVEH6cV5K9l1YCVhgV7Ah1NW8YrBD+l40=,tag:+rSwk+lnEnYoEALI9eCT+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10cfaarw2s7u823kc44fwm8fjzr8c8hnukayd4f948da22nwx7vvqurhcuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUHBpT09CbmdBREZSdm9D
            cUlVVjlKTmkyT1dTd2Jtb2grTkZhNS9XTlhjCnZoL3QzaHpOOHFoYXdIalVHbmdj
            OFBoQmszeUQ0ZkZvNjBqbFJrTmlFVXMKLS0tIFVVYmRiL0plcDVwWEF0WmR4dnhR
            WjZ2Y2RtSlRFUnk2aGtZSTlyNU9QL0UKTqql2c1GPb6rUMPtTiWYh5xPTcCtpOfU
            oeFW83EFRWtf69j0aXKzHwgElA31YTnixNYusOQbj1yq412p/JL+RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-12T00:32:51Z"
    mac: ENC[AES256_GCM,data:x2dCOjVionmtEUmFqB9yqd3mBrIo7Z6ilyc0BJMQyqlpBBpEA2g8RfVkbBrbNV/kkteDprfdM/YYcCtp9vkrkEwhtgI4yMEvggNxwYRY/5vBH5KLrDuXWWfWAyQkXBvxb2Mwyipk44W7RqQTPcMnifc9zcowLO9Kueir4QyEdcU=,iv:3sxglkguT4OPYMXpuDXNuo1hrc1BOBDEKfwmd5rRdfc=,tag:sbiY9gTHWraZQrJaLD+7Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
